### ISSUE TITLE
Installing Dependencies with Composer

### ISSUE THREAD

**Issue by ericktheredd** [ppi/skeletonapp#20]
I get the following error when trying to install the framework dependencies, using Composer:

"
Loading composer repositories with package information
Installing dependencies
  - Installing smarty/smarty (v3.1.12)
    Checking out /tags/v3.1.12/@4664

Package could not be downloaded, 'svn' is not recognized as an internal or external command
"
Any ideas?

**Comment by dragoonis** [comment]
@noisebleed does the smarty packagist library still require a SVN download? We should discuss this to see if we can provide a git alternative, or even a github.com/ppi/smarty mirror for git downloading.
