### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by interlan** [ppi/skeletonapp#28]
Win XP SP3, local wamp server (usbswebserver) on drive H:, server root is usbswebserver/root, installation directory ppiskeletonapp. Pointing at localhost/ppiskeletonapp/public gives out : 

Unable to find composer generated file at: H:\usbswebserver\root\ppiskeletonapp/vendor/autoload.php

some fix please!

regards
Petros

**Comment by dragoonis** [comment]
@interlan you still using PPI ? did you solve this problem at all ?
