### ISSUE TITLE
userEntity wrong defined

### ISSUE THREAD

**Issue by kamov** [ppi/skeletonapp#30]
the userEntity seem wrong defined

            'userEntity' => function($sm) {
               return new UserModule\Entity\User();
            }

since we are already on namespace UserModule, then should be:

            'userEntity' => function($sm) {
               return new Entity\User();
            }

and entity user require to pass $data, is correct this:

            'userEntity' => function($sm) {
               return new Entity\User($this->getSession()->get('ppiAuthUser'));
            }

Thanks!!

**Comment by dragoonis** [comment]
@kamov you still using PPI ? did this issue get resolved for you at all ?
